name: windows ai

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 60  # Set a reasonable timeout

    steps:
    - name: Download Ngrok
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/cubinz/rdpmeens/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/cubinz/rdpmeens/main/wallpaper.png -OutFile wallpaper.png
        Invoke-WebRequest https://raw.githubusercontent.com/cubinz/rdpmeens/main/wallpaper.bat -OutFile wallpaper.bat
        Invoke-WebRequest https://raw.githubusercontent.com/cubinz/rdpmeens/main/loop.bat -OutFile loop.bat

    - name: Download Launcher
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/cubinz/rdpmeens/main/launcher/Node.js.lnk -OutFile Node.js.lnk
        Invoke-WebRequest https://raw.githubusercontent.com/cubinz/rdpmeens/main/launcher/Visual%20Studio%202019.lnk -OutFile "Visual Studio 2019.lnk"
        Invoke-WebRequest https://github.com/cubinz/rdpmeens/raw/main/launcher/Ganti%20Password.exe -OutFile "Ganti Password.exe"

    - name: Extract Ngrok File
      run: Expand-Archive ngrok.zip -DestinationPath .\ngrok

    - name: Connect Ngrok
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Action Access RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
        Copy-Item wallpaper.png D:\a\wallpaper.png
        Copy-Item wallpaper.bat D:\a\wallpaper.bat
        Copy-Item Node.js.lnk C:\Users\Public\Desktop\Node.js.lnk
        Copy-Item "Visual Studio 2019.lnk" "C:\Users\Public\Desktop\Visual Studio 2019.lnk"
        Copy-Item "Ganti Password.exe" "C:\Users\Public\Desktop\Ganti Password.exe"

    - name: Start Ngrok Tunnel
      id: ngrok
      run: |
        Start-Process PowerShell -ArgumentList '-NoExit', '-Command', ".\ngrok\ngrok.exe tcp --region=ap 3389" -PassThru | Out-File ngrok_output.txt
        Start-Sleep -Seconds 10  # Wait for ngrok to start
        $ngrokUrl = Get-Content ngrok_output.txt | Select-String -Pattern "https://[a-z0-9\.]+"
        Write-Output "Public URL: $ngrokUrl"

    - name: Connect RDP CPU 2 Core - 7GB Ram - 256 SSD
      run: cmd /c start.bat

    - name: Successful implementation! You can close the tab now.
      run: cmd /c loop.bat
